(define (cons x y)
    (lambda (m) (m x y)))
(define (car z)
    (z (lambda (p q) p)))
(define a (cons 2 3))
;; a = (lambda (m) (m 2 3))
(car a) 
;; (car a) 
;; = (a (lambda (p q) p)) 
;; = ((lambda (m) (m 2 3)) (lambda (p q) p))
;; = ((lambda (p q) p) 2 3)
;; = 2
(define (cdr z)
    (z (lambda (p q) q)))
(cdr a)
