(define tolerance 0.00001)
(define (close_enough? x y)
    (< (abs (- x y)) tolerance))
(define (fixed_point f first_guess)
    (define (try guess)
        (let ((next (f guess)))
            (if (close_enough? guess next)
                next
                (try next))))
    (try first_guess))
(fixed_point (lambda (x) (+ 1 (/ 1 x))) 1.0)