(define us_coins (list 50 25 10 5 1))
(define uk_coins (list 100 50 20 10 5 2 1 0.5))
(define (no_more? coin_values)
    (null? coin_values))
(define (except_first_denomination coin_values)
    (cdr coin_values))
(define (first_denomination coin_values)
    (car coin_values))
(define (cc amount coin_values)
    (cond ((= amount 0) 1)
          ((or (< amount 0) (no_more? coin_values)) 0)
          (else (+ (cc  amount 
                        (except_first_denomination coin_values))
                   (cc  (- amount (first_denomination coin_values))
                        coin_values)))))
(cc 100 us_coins)