(define balance 100)
(define (withdraw amount)
    (if (>= balance amount)
        (begin (set! balance (- balance amount))
               balance)
        "Insufficient funds"))

(define new_withdraw
    (let ((balance 100))
        (lambda (amount)
            (if (>= balance amount)
                (begin (set! balance (- balance amount))
                       balance)
                "Insufficient funds"))))
(define (make_withdraw balance)
    (lambda (amount)
        (if (>= balance amount)
            (begin (set! balance (- balance amount))
                       balance)
                "Insufficient funds")))
(define W1 (make_withdraw 100))
(define W2 (make_withdraw 100))

(W1 50)
(W2 70)
(W2 40)
(W1 40)