(define (square x)
    (* x x))
(define (sum_squares x y)
    (+ (square x) (square y)))
(define (sum_square_larger a b c)
    (cond   ((> a c) (> b c) (sum_squares a b))
        ((> a b) (> c b) (sum_squares a c))
        (else (sum_squares b c))))
(sum_square_larger 1 2 3)