(define (make_account password balance)
    (define (withdraw amount)
        (if (>= balance amount)
            (begin (set! balance (- balance amount))
                       balance)
                "Insufficient funds"))
    (define (deposit amount)
        (set! balance (+ balance amount))
        balance)
    (define (warning _)
        "Incorrect password")
    (define (dispatch p m)
        (cond ((not (eq? p password)) warning)
              ((eq? m 'withdraw) withdraw)
              ((eq? m 'deposit) deposit)
              (else (error "Unknown request:  MAKE_ACCOUNT" m))))
    dispatch)
(define acc (make_account '123 100))
((acc '123 'withdraw) 50)
((acc '12 'withdraw) 60)
((acc '123 'deposit) 40)
((acc '123 'withdraw) 60)