(define (make_account password balance)
    (define (withdraw amount)
        (if (>= balance amount)
            (begin (set! balance (- balance amount))
                       balance)
                "Insufficient funds"))
    (define (deposit amount)
        (set! balance (+ balance amount))
        balance)
    (define (warning _)
        "Incorrect password")
    (define (dispatch p m)
        (cond ((not (eq? p password)) warning)
              ((eq? m 'withdraw) withdraw)
              ((eq? m 'deposit) deposit)
              (else (error "Unknown request:  MAKE_ACCOUNT" m))))
    dispatch)
(define acc (make_account '123 100))

(define (make_joint account oldPassword newPassword)
    (define (warning _)
        "Incorrect password")
    (lambda (p m)
        (cond ((not (eq? p newPassword)) warning)
              (else (account oldPassword m)))))
(define paul_acc
    (make_joint acc '123 '345))
((paul_acc '345 'withdraw) 10)
((paul_acc '3415 'withdraw) 10)
((paul_acc '345 'withdraw) 10)